# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d856d539a212141f2921b1a1086bb1d6"
name = "DC Echo Eraser"
handle = "dc-echo-eraser"
application_url = "https://showers-relationships-segments-area.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://showers-relationships-segments-area.trycloudflare.com/auth/callback",
  "https://showers-relationships-segments-area.trycloudflare.com/auth/shopify/callback",
  "https://showers-relationships-segments-area.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
